#getting base image from ubuntu
FROM ubuntu

#optional but mentioning maintainer name preferable email address
MAINTAINER ratna <ratnasrinivas1992@gmail.com>

#run command creating a file 
RUN apt-get update

#displaying the content
CMD ["echo","file created... my first docker image"]



